settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 3001 
  host: localhost
schema:
- name: clean-architecture-go
  path: .
  commands: 
  run:
    status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
