version: "3.1"
servuices:
  web:
    container_name: go_clean_web
    build: ./ui
    ports: 
      - "3000:3000"
  api:
    container_name: go_clean_api 
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db 
  db:
    image: postgres
    container_name: go_clean_arch_psql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres 
